In [1]:
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt # plotting
import numpy as np # linear algebra
import os # accessing directory structure
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [8]:
df_train=pd.read_csv('C:/Users/mota1/Downloads/train.csv')
df_test=pd.read_csv('C:/Users/mota1/Downloads/train.csv')

In [10]:
dataset = pd.concat([df_train, df_test], axis=0)

In [11]:
dataset

profile pic  nums/length username  fullname words  nums/length fullname  \
0              1                  0.27               0                  0.00   
1              1                  0.00               2                  0.00   
2              1                  0.10               2                  0.00   
3              1                  0.00               1                  0.00   
4              1                  0.00               2                  0.00   
..           ...                   ...             ...                   ...   
571            1                  0.55               1                  0.44   
572            1                  0.38               1                  0.33   
573            1                  0.57               2                  0.00   
574            1                  0.57               1                  0.00   
575            1                  0.27               1                  0.00   

     name==username  description length  external URL  private  #posts  \
0                 0                  53             0        0      32   
1                 0                  44             0        0     286   
2                 0                   0             0        1      13   
3                 0                  82             0        0     679   
4                 0                   0             0        1       6   
..              ...                 ...           ...      ...     ...   
571               0                   0             0        0      33   
572               0                  21             0        0      44   
573               0                   0             0        0       4   
574               0                  11             0        0       0   
575               0                   0             0        0       2   

     #followers  #follows  fake  
0          1000       955     0  
1          2740       533     0  
2           159        98     0  
3           414       651     0  
4           151       126     0  
..          ...       ...   ...  
571         166       596     1  
572          66        75     1  
573          96       339     1  
574          57        73     1  
575         150       487     1  

[1152 rows x 12 columns]

In [13]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1152 entries, 0 to 575
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   profile pic           1152 non-null   int64  
 1   nums/length username  1152 non-null   float64
 2   fullname words        1152 non-null   int64  
 3   nums/length fullname  1152 non-null   float64
 4   name==username        1152 non-null   int64  
 5   description length    1152 non-null   int64  
 6   external URL          1152 non-null   int64  
 7   private               1152 non-null   int64  
 8   #posts                1152 non-null   int64  
 9   #followers            1152 non-null   int64  
 10  #follows              1152 non-null   int64  
 11  fake                  1152 non-null   int64  
dtypes: float64(2), int64(10)
memory usage: 117.0 KB


In [14]:
dataset.describe()

profile pic  nums/length username  fullname words  \
count  1152.000000           1152.000000     1152.000000   
mean      0.701389              0.163837        1.460069   
std       0.457848              0.214003        1.052143   
min       0.000000              0.000000        0.000000   
25%       0.000000              0.000000        1.000000   
50%       1.000000              0.000000        1.000000   
75%       1.000000              0.310000        2.000000   
max       1.000000              0.920000       12.000000   

       nums/length fullname  name==username  description length  external URL  \
count           1152.000000     1152.000000         1152.000000   1152.000000   
mean               0.036094        0.034722           22.623264      0.116319   
std                0.125066        0.183155           37.686605      0.320747   
min                0.000000        0.000000            0.000000      0.000000   
25%                0.000000        0.000000            0.000000      0.000000   
50%                0.000000        0.000000            0.000000      0.000000   
75%                0.000000        0.000000           34.000000      0.000000   
max                1.000000        1.000000          150.000000      1.000000   

           private       #posts    #followers     #follows         fake  
count  1152.000000  1152.000000  1.152000e+03  1152.000000  1152.000000  
mean      0.381944   107.489583  8.530724e+04   508.381944     0.500000  
std       0.486074   401.859747  9.097530e+05   917.582377     0.500217  
min       0.000000     0.000000  0.000000e+00     0.000000     0.000000  
25%       0.000000     0.000000  3.900000e+01    57.500000     0.000000  
50%       0.000000     9.000000  1.505000e+02   229.500000     0.500000  
75%       1.000000    81.500000  7.160000e+02   589.500000     1.000000  
max       1.000000  7389.000000  1.533854e+07  7500.000000     1.000000

In [16]:
dataset['#followers'] = np.log1p(dataset['#followers'])
dataset['#posts'] = np.log1p(dataset['#posts'])

In [17]:
X=dataset.drop(columns=['fake'])
y=dataset['fake']

In [21]:
X.drop(columns=['nums/length fullname','name==username'], inplace=True)

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)


In [23]:
X

profile pic  nums/length username  fullname words  description length  \
0              1                  0.27               0                  53   
1              1                  0.00               2                  44   
2              1                  0.10               2                   0   
3              1                  0.00               1                  82   
4              1                  0.00               2                   0   
..           ...                   ...             ...                 ...   
571            1                  0.55               1                   0   
572            1                  0.38               1                  21   
573            1                  0.57               2                   0   
574            1                  0.57               1                  11   
575            1                  0.27               1                   0   

     external URL  private    #posts  #followers  #follows  
0               0        0  3.496508    6.908755       955  
1               0        0  5.659482    7.916078       533  
2               0        1  2.639057    5.075174        98  
3               0        0  6.522093    6.028279       651  
4               0        1  1.945910    5.023881       126  
..            ...      ...       ...         ...       ...  
571             0        0  3.526361    5.117994       596  
572             0        0  3.806662    4.204693        75  
573             0        0  1.609438    4.574711       339  
574             0        0  0.000000    4.060443        73  
575             0        0  1.098612    5.017280       487  

[1152 rows x 9 columns]

In [24]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)


In [25]:
X


profile pic  nums/length username  fullname words  description length  \
0              1                  0.27               0                  53   
1              1                  0.00               2                  44   
2              1                  0.10               2                   0   
3              1                  0.00               1                  82   
4              1                  0.00               2                   0   
..           ...                   ...             ...                 ...   
571            1                  0.55               1                   0   
572            1                  0.38               1                  21   
573            1                  0.57               2                   0   
574            1                  0.57               1                  11   
575            1                  0.27               1                   0   

     external URL  private    #posts  #followers  #follows  
0               0        0  3.496508    6.908755       955  
1               0        0  5.659482    7.916078       533  
2               0        1  2.639057    5.075174        98  
3               0        0  6.522093    6.028279       651  
4               0        1  1.945910    5.023881       126  
..            ...      ...       ...         ...       ...  
571             0        0  3.526361    5.117994       596  
572             0        0  3.806662    4.204693        75  
573             0        0  1.609438    4.574711       339  
574             0        0  0.000000    4.060443        73  
575             0        0  1.098612    5.017280       487  

[1152 rows x 9 columns]

In [26]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = "entropy", random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [27]:
y_pred  = classifier.predict(X_test)

In [28]:
y_pred

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1], dtype=int64)

In [29]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)


In [30]:
cm

array([[131,   1],
       [  7, 149]], dtype=int64)

In [35]:
280/288


0.9722222222222222

In [32]:
X_test


array([[ 0.63989192,  0.68226932, -0.4561413 , ..., -1.20387062,
        -0.79630959, -0.52246735],
       [ 0.63989192,  1.35295032, -0.4561413 , ...,  0.8504264 ,
        -0.20945873, -0.37529316],
       [-1.56276392,  0.29902304, -0.4561413 , ..., -1.20387062,
        -0.50815221, -0.563105  ],
       ...,
       [-1.56276392,  1.16132718, -0.4561413 , ..., -1.20387062,
        -0.78028281, -0.46645329],
       [ 0.63989192, -0.75490425,  0.5242221 , ...,  1.11306414,
         0.84830707,  1.50392352],
       [-1.56276392,  0.29902304, -1.43650471, ..., -0.13914746,
        -1.61270138, -0.32696731]])

280