<h3>Imports</h3>

In [3]:
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt # plotting
import numpy as np # linear algebra
import os # accessing directory structure
import pandas as pd # data processing, CSV

<h3>Cargamos los dataset</h3>

In [4]:
df_train=pd.read_csv('C:/Users/mota1/Downloads/train.csv')
df_test=pd.read_csv('C:/Users/mota1/Downloads/train.csv')

Unimos los dataset 

In [5]:
dataset = pd.concat([df_train, df_test], axis=0)

<h3>Analisis exploratorio del dataset</h3>

In [6]:
dataset

profile pic  nums/length username  fullname words  nums/length fullname  \
0              1                  0.27               0                  0.00   
1              1                  0.00               2                  0.00   
2              1                  0.10               2                  0.00   
3              1                  0.00               1                  0.00   
4              1                  0.00               2                  0.00   
..           ...                   ...             ...                   ...   
571            1                  0.55               1                  0.44   
572            1                  0.38               1                  0.33   
573            1                  0.57               2                  0.00   
574            1                  0.57               1                  0.00   
575            1                  0.27               1                  0.00   

     name==username  description length  external URL  private  #posts  \
0                 0                  53             0        0      32   
1                 0                  44             0        0     286   
2                 0                   0             0        1      13   
3                 0                  82             0        0     679   
4                 0                   0             0        1       6   
..              ...                 ...           ...      ...     ...   
571               0                   0             0        0      33   
572               0                  21             0        0      44   
573               0                   0             0        0       4   
574               0                  11             0        0       0   
575               0                   0             0        0       2   

     #followers  #follows  fake  
0          1000       955     0  
1          2740       533     0  
2           159        98     0  
3           414       651     0  
4           151       126     0  
..          ...       ...   ...  
571         166       596     1  
572          66        75     1  
573          96       339     1  
574          57        73     1  
575         150       487     1  

[1152 rows x 12 columns]

Revisamos los tipos de variables y de datos en el dataset 

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1152 entries, 0 to 575
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   profile pic           1152 non-null   int64  
 1   nums/length username  1152 non-null   float64
 2   fullname words        1152 non-null   int64  
 3   nums/length fullname  1152 non-null   float64
 4   name==username        1152 non-null   int64  
 5   description length    1152 non-null   int64  
 6   external URL          1152 non-null   int64  
 7   private               1152 non-null   int64  
 8   #posts                1152 non-null   int64  
 9   #followers            1152 non-null   int64  
 10  #follows              1152 non-null   int64  
 11  fake                  1152 non-null   int64  
dtypes: float64(2), int64(10)
memory usage: 117.0 KB


In [8]:
dataset.describe()

profile pic  nums/length username  fullname words  \
count  1152.000000           1152.000000     1152.000000   
mean      0.701389              0.163837        1.460069   
std       0.457848              0.214003        1.052143   
min       0.000000              0.000000        0.000000   
25%       0.000000              0.000000        1.000000   
50%       1.000000              0.000000        1.000000   
75%       1.000000              0.310000        2.000000   
max       1.000000              0.920000       12.000000   

       nums/length fullname  name==username  description length  external URL  \
count           1152.000000     1152.000000         1152.000000   1152.000000   
mean               0.036094        0.034722           22.623264      0.116319   
std                0.125066        0.183155           37.686605      0.320747   
min                0.000000        0.000000            0.000000      0.000000   
25%                0.000000        0.000000            0.000000      0.000000   
50%                0.000000        0.000000            0.000000      0.000000   
75%                0.000000        0.000000           34.000000      0.000000   
max                1.000000        1.000000          150.000000      1.000000   

           private       #posts    #followers     #follows         fake  
count  1152.000000  1152.000000  1.152000e+03  1152.000000  1152.000000  
mean      0.381944   107.489583  8.530724e+04   508.381944     0.500000  
std       0.486074   401.859747  9.097530e+05   917.582377     0.500217  
min       0.000000     0.000000  0.000000e+00     0.000000     0.000000  
25%       0.000000     0.000000  3.900000e+01    57.500000     0.000000  
50%       0.000000     9.000000  1.505000e+02   229.500000     0.500000  
75%       1.000000    81.500000  7.160000e+02   589.500000     1.000000  
max       1.000000  7389.000000  1.533854e+07  7500.000000     1.000000

<h3>Preprocesamiento de datos</h3>

Eliminamos las columnas con datos poco relevantes y se separa el dataset en X (variables independientes) y Y (variable dependiente) 

In [9]:
X=dataset.drop(columns=['fake'])
y=dataset['fake']

In [10]:
X.drop(columns=['nums/length fullname','name==username'], inplace=True)

In [11]:
dataset['#followers'] = np.log1p(dataset['#followers'])
dataset['#posts'] = np.log1p(dataset['#posts'])

Dividir el data set en conjunto de entrenamiento y conjunto de testing

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)


In [13]:
X

profile pic  nums/length username  fullname words  description length  \
0              1                  0.27               0                  53   
1              1                  0.00               2                  44   
2              1                  0.10               2                   0   
3              1                  0.00               1                  82   
4              1                  0.00               2                   0   
..           ...                   ...             ...                 ...   
571            1                  0.55               1                   0   
572            1                  0.38               1                  21   
573            1                  0.57               2                   0   
574            1                  0.57               1                  11   
575            1                  0.27               1                   0   

     external URL  private  #posts  #followers  #follows  
0               0        0      32        1000       955  
1               0        0     286        2740       533  
2               0        1      13         159        98  
3               0        0     679         414       651  
4               0        1       6         151       126  
..            ...      ...     ...         ...       ...  
571             0        0      33         166       596  
572             0        0      44          66        75  
573             0        0       4          96       339  
574             0        0       0          57        73  
575             0        0       2         150       487  

[1152 rows x 9 columns]

Escalado de variables

In [18]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)


In [19]:
X_train

array([[-1.56276392,  1.35295032, -0.4561413 , ..., -0.25086927,
        -0.09086684, -0.53235218],
       [ 0.63989192, -0.75490425,  0.5242221 , ..., -0.17071727,
        -0.08940289, -0.50599263],
       [-1.56276392, -0.75490425,  0.5242221 , ..., -0.25086927,
        -0.09092241, -0.36870327],
       ...,
       [ 0.63989192, -0.75490425,  0.5242221 , ..., -0.06162149,
        -0.09024752,  0.10576874],
       [ 0.63989192,  1.64038504, -0.4561413 , ..., -0.22415194,
        -0.09084462, -0.444487  ],
       [ 0.63989192, -0.75490425,  0.5242221 , ...,  0.49276319,
        -0.09045867, -0.13476221]])

<h3>Modelado</h3>
Ajustar el clasificador Random Forest y XGBoost en el Conjunto de Entrenamiento

<h3>Random Forest</h3>

In [20]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = "entropy", random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

Predicción de los resultados con el Conjunto de Testing

In [21]:
y_pred  = classifier.predict(X_test)

In [22]:
y_pred

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1], dtype=int64)

Elaborar una matriz de confusión

In [36]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[131,   1],
       [  7, 149]], dtype=int64)

In [28]:
print ("RF Training score:",classifier.score(X_train,y_train),"Test Score:", classifier.score(X_test,y_test))

RF Training score: 0.9976851851851852 Test Score: 0.9722222222222222


<h3>XGBoost</h3>

In [30]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [31]:
y_xgb_pred  = xgb.predict(X_test)

In [33]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_xgb_pred)
cm

array([[130,   2],
       [  4, 152]], dtype=int64)

In [34]:
print ("xgboost Training score:",xgb.score(X_train,y_train),"Test Score:", xgb.score(X_test,y_test))

xgboost Training score: 1.0 Test Score: 0.9791666666666666
